INSTALL_PATH = /usr/local/bin

install:
	mkdir -p ${INSTALL_PATH}
	cp -f dwm_bar ${INSTALL_PATH}
	chmod 755 ${INSTALL_PATH}/dwm_bar

uninstall:
	rm -f ${INSTALL_PATH}/dwm_bar

.PHONY: install uninstall

